//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajePlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public int IdHotel { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Planes Planes { get; set; }
        public virtual Reservaciones Reservaciones { get; set; }
    }
}
